/* Objective: register the current Aloe action surface in one place so UI and agent logic can scale dynamically. */

import type { AloeActionDefinition } from "@/lib/aloe/actions/types";

export const ALOE_ACTION_REGISTRY: AloeActionDefinition[] = [
  {
    key: "generate_setup_manifest",
    label: "Generate setup manifest",
    category: "planning",
    executionModes: ["connected_execution", "external_implementation"],
    producedArtifact: "setup_manifest",
    prerequisites: [],
    rerunnable: true,
    visibleInViews: ["operator_mission_control", "executive_summary"],
    description: "Create the initial managed setup manifest for the session.",
  },
  {
    key: "generate_env_propagation",
    label: "Generate environment propagation",
    category: "infrastructure",
    executionModes: ["connected_execution"],
    producedArtifact: "environment_propagation",
    prerequisites: [],
    rerunnable: true,
    visibleInViews: ["operator_mission_control"],
    description: "Prepare environment mappings from provisioned resources into the app runtime.",
  },
  {
    key: "sync_vercel_env",
    label: "Sync Vercel environment",
    category: "infrastructure",
    executionModes: ["connected_execution"],
    producedArtifact: "environment_sync",
    prerequisites: ["environment_propagation"],
    rerunnable: true,
    visibleInViews: ["operator_mission_control"],
    description: "Sync public environment variables into Vercel.",
  },
  {
    key: "save_secret_input",
    label: "Save secret input",
    category: "infrastructure",
    executionModes: ["connected_execution"],
    producedArtifact: "secret_input",
    prerequisites: [],
    rerunnable: true,
    visibleInViews: ["operator_mission_control"],
    description: "Capture required secret values for downstream sync.",
  },
  {
    key: "sync_vercel_secrets",
    label: "Sync Vercel secrets",
    category: "infrastructure",
    executionModes: ["connected_execution"],
    producedArtifact: "secret_sync",
    prerequisites: ["secret_input"],
    rerunnable: true,
    visibleInViews: ["operator_mission_control"],
    description: "Sync private environment secrets into Vercel.",
  },
  {
    key: "generate_stripe_connection",
    label: "Generate Stripe connection",
    category: "billing",
    executionModes: ["connected_execution", "external_implementation"],
    producedArtifact: "stripe_connection",
    prerequisites: [],
    rerunnable: true,
    visibleInViews: ["operator_mission_control", "executive_summary"],
    description: "Capture Stripe ownership and connector state.",
  },
  {
    key: "generate_stripe_validation",
    label: "Generate Stripe validation",
    category: "billing",
    executionModes: ["connected_execution", "external_implementation"],
    producedArtifact: "stripe_validation",
    prerequisites: ["stripe_connection"],
    rerunnable: true,
    visibleInViews: ["operator_mission_control"],
    description: "Validate Stripe key, webhook, and environment readiness.",
  },
  {
    key: "generate_stripe_handoff",
    label: "Generate Stripe handoff",
    category: "billing",
    executionModes: ["connected_execution", "external_implementation"],
    producedArtifact: "stripe_handoff",
    prerequisites: ["stripe_connection", "stripe_validation"],
    rerunnable: true,
    visibleInViews: ["operator_mission_control", "client_handoff"],
    description: "Package Stripe state for downstream execution and handoff.",
  },
  {
    key: "generate_bootstrap_readiness",
    label: "Generate bootstrap readiness",
    category: "infrastructure",
    executionModes: ["connected_execution"],
    producedArtifact: "bootstrap_readiness",
    prerequisites: ["environment_propagation", "environment_sync", "secret_sync", "stripe_handoff"],
    rerunnable: true,
    visibleInViews: ["operator_mission_control", "executive_summary"],
    description: "Compute whether the connected system is ready for app hookup and deployment.",
  },
  {
    key: "generate_app_bootstrap",
    label: "Generate app bootstrap",
    category: "planning",
    executionModes: ["connected_execution"],
    producedArtifact: "app_bootstrap",
    prerequisites: ["bootstrap_readiness"],
    rerunnable: true,
    visibleInViews: ["operator_mission_control", "executive_summary"],
    description: "Generate app-level deployment inputs from the connected stack.",
  },
  {
    key: "generate_execution_envelope",
    label: "Generate execution envelope",
    category: "planning",
    executionModes: ["connected_execution", "external_implementation"],
    producedArtifact: "execution_envelope",
    prerequisites: [],
    rerunnable: true,
    visibleInViews: ["operator_mission_control", "executive_summary"],
    description: "Resolve execution mode and required outputs from Starling-to-Aloe context.",
  },
  {
    key: "generate_deployment_source_connection",
    label: "Generate deployment source connection",
    category: "deployment",
    executionModes: ["connected_execution", "external_implementation"],
    producedArtifact: "deployment_source_connection",
    prerequisites: ["app_bootstrap", "execution_envelope"],
    rerunnable: true,
    visibleInViews: ["operator_mission_control"],
    description: "Describe the source repo/branch/framework connection for deployment.",
  },
  {
    key: "generate_first_deployment_trigger",
    label: "Generate first deployment trigger",
    category: "deployment",
    executionModes: ["connected_execution"],
    producedArtifact: "first_deployment_trigger",
    prerequisites: ["deployment_source_connection"],
    rerunnable: true,
    visibleInViews: ["operator_mission_control"],
    description: "Prepare the first deployment trigger plan.",
  },
  {
    key: "generate_first_deployment_execution",
    label: "Generate first deployment execution",
    category: "deployment",
    executionModes: ["connected_execution"],
    producedArtifact: "first_deployment_execution",
    prerequisites: ["first_deployment_trigger"],
    rerunnable: true,
    visibleInViews: ["operator_mission_control"],
    description: "Capture the first real deployment execution result.",
  },
  {
    key: "generate_post_deployment_validation",
    label: "Generate post deployment validation",
    category: "deployment",
    executionModes: ["connected_execution"],
    producedArtifact: "post_deployment_validation",
    prerequisites: ["first_deployment_execution"],
    rerunnable: true,
    visibleInViews: ["operator_mission_control", "client_handoff"],
    description: "Validate that the live deployment is working as expected.",
  },
  {
    key: "generate_client_handoff",
    label: "Generate client handoff",
    category: "handoff",
    executionModes: ["connected_execution", "external_implementation"],
    producedArtifact: "client_handoff",
    prerequisites: ["post_deployment_validation", "stripe_handoff"],
    rerunnable: true,
    visibleInViews: ["operator_mission_control", "client_handoff", "executive_summary"],
    description: "Create the client-ready handoff summary.",
  },
  {
    key: "generate_client_handoff_export",
    label: "Generate client handoff export",
    category: "handoff",
    executionModes: ["connected_execution", "external_implementation"],
    producedArtifact: "client_handoff_export",
    prerequisites: ["client_handoff"],
    rerunnable: true,
    visibleInViews: ["operator_mission_control", "client_handoff", "executive_summary"],
    description: "Generate the exportable handoff package.",
  },
];

export const ALOE_ACTION_REGISTRY_BY_KEY = Object.fromEntries(
  ALOE_ACTION_REGISTRY.map((action) => [action.key, action]),
);
